absolute_urls: false

home:
  alias: '/home'

pages:
  theme: uf
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: false
  js_pipeline: true
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true
gpm:
  verify_peer: true
